name: CI/CD: Docker Compose Build & Run

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  docker-compose-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image with Compose
      run: docker-compose build

    - name: Run Docker Container with Compose
      run: docker-compose up -d
